### ISSUE TITLE
npm registery

### ISSUE THREAD

**Issue by dortzur** [Formstone/Formstone#1]
Hey,
Although a package.json file exist, I think you have yet to update the npm registery
https://www.npmjs.com/search?q=formstone

would be great if you could do that.

Thanks!

**Comment by benplum** [comment]
It's registered on bower (http://bower.io/search/?q=formstone). I'll look in to registering it with npm as well.

**Comment by benplum** [comment]
I went ahead and registered the package with npm (https://www.npmjs.com/package/formstone), but Bower is still preferred since it only installs the files required for front end implementation and does not require special publishing (runs off standard git repos). You may also need to build a bridge since the library does not use require.js. This is a great post on npm vs front-end specific registries, like Bower:

http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging
