### ISSUE TITLE
Carousel Scroll by multiple of items

### ISSUE THREAD

**Issue by nickngqs** [Formstone/Formstone#197]
How do I scroll multiple of items as well as control number of items based on screen size?

Currently I'm checking a index to jump to a particular page.

```
var currIndex = 1

// There is 4 slides visible each time
$('button').click(function(){
var nextIndex = currIndex + 4
$(".target").carousel("jump", nextIndex);
});

```

Somehow this is giving me alot of quirks and so on. Just wondering is there is a better way to do this?

**Comment by benplum** [comment]
I think the issue is that the 'page' and 'item' indexes are different depending on how many items are visible at a specific break point. The `jump` method is going to be based on page index, where as you are looking to jump to a specific item, which may have a different page index. I think adding a new method that would allow you to jump to a specific item index would be the way to go. 

As a short term solution until the new method is release, you can always calculate the page index yourself (assuming you also know how many items should be visible at the current breakpoint size):

```
var windowWidth = $(window).width();
var itemIndex = $(".item").index();
var perPage = 1;

// Show 2 pages on tablet
if (windowWidth >= 740) {
    perPage = 2;
}
// Show 3 pages on desktop
if (windowWidth >= 980) {
    perPage = 3;
}

// Final page index
var pageIndex = Math.floor( pageIndex / 1 );
$(".target").carousel("jump", pageIndex);
```

**Comment by nickngqs** [comment]
Thanks! :)

Definitely would be great if that could be added especially in a responsive point of view.

For example

```
slideToShow
slideToScroll
```

Thanks once again!

**Comment by benplum** [comment]
There will be a new `jumpItem` method in the next release that lets you jump to a specific item. We've also aliased the old jump methods for more clarity around what they actually do:

```
$(".target").carousel("jumpItem", 2); // Jump to second item
$(".target").carousel("jumpPage", 2); // Jump to second page, alias of `jump`
$(".target").carousel("previousPage"); // Jump to previous page, alias of `previous`
$(".target").carousel("nextPage"); // Jump to next page, alias of `next`
```

You can check it out on the dev branch.
