### ISSUE TITLE
Remove browser agent sniffing in favor of media queries for lightbox.js

### ISSUE THREAD

**Issue by mimoduo** [Formstone/Formstone#234]
This would make it way easier to style!

Sincerely,
Bryan Stoner

**Comment by benplum** [comment]
Is this specifically for the 'mobile' display mode? One of the reasons it's classed based is that you can force the 'mobile' mode on desktop sized screens, but it's always forced on mobile devices (even larger devices, like iPads). I agree browser sniffing isn't great and would be open to suggestions that keep the existing functionality.

**Comment by mimoduo** [comment]
I'll start with what I notice: Usually I'll bring up my phone with browser sync connected to the site and then guess the mobile selector I need to style by comparing with the source lightbox.less file and then writing in some test css. I'm not sure if the markup is different too (the view caption toggle is there on mobile) but being able to test within the browser would be a boat load of awesome!

My own thought at the moment would be to keep everything the same but switch out a "mobile" class on the markup based on a particular screen width. That could then be an option similar to mobile: true; false meaning the class is never applied. I'd love to hear what you think ;)

**Comment by benplum** [comment]
Testing with browser sync is great, but you can also test using [Chrome's device mode](https://developers.google.com/web/tools/chrome-devtools/device-mode/). 

The markup and positioning calculations do change slightly between 'desktop' and 'mobile' rendering (including Viewer can also change markup as well). The 'traditional' lightbox should never render on a touch-enabled device, even if it has a larger screen (like an iPad or Surface). Browser sniffing is used to ensure the 'mobile' display mode is triggered on those devices (Windows touch-enabled laptops screw with feature detection, since they technically support both input methods at once).

Here's a rundown of how the different display modes work:

Default Settings (`mobile: false`):
* Traditional lightbox rendering on 'desktop' devices
* Full screen overlay rendering on 'mobile' devices, optimized for touch

Mobile Settings (`mobile: true`):
* Full screen overlay rendering on all devices, optimized for touch on 'mobile devices'

I think using the term `mobile` as the option name is misleading since you can trigger that display mode on a 'desktop' device. We've been considering renaming it to `overlay` in a future release and are open to suggestions!

**Comment by benplum** [comment]
Switched the 'mobile' option to 'overlay'. Classes might change next, but hopefully this helps with any confusion around config options.
