### ISSUE TITLE
Accessibility Enhancement: Carousel Controls

### ISSUE THREAD

**Issue by nhall** [Formstone/Formstone#236]
I've run into a potential accessibility problem when displaying multiple carousels on the same page. Using [Siteimprove](https://siteimprove.com/) on a page with multiple carousels I get an error that there are multiple landmarks on the page with identical names. Full error:

> 1.3 Adaptable
> 1.3.1 Info and Relationships
> Landmarks with identical names
> 
> Two or more HTML5 or WAI-ARIA landmarks have identical names. Users might not know the difference if it's not somehow explained.
> 
> Use unique names for each landmark on the page.

The problem is with the carousel pagination. All carousel pagination elements have the `aria-label` of "carousel pagination". This is too generic as a screen reader will announce all of the instance of these landmarks the same.

I think we should make this configurable? It's tough as not all carousels have a specific title but there should be some way to make this unique.

Thanks!

**Comment by benplum** [comment]
We do have internal GUIDs for each instance, would something like 'carousel 12 pagination' and 'carousel 12 controls' be sufficient, or would you rather have fine grain control? 

EDIT: I suppose making them customizable would help with localization.

**Comment by benplum** [comment]
Went ahead and added new labeling options in Carousel, Lightbox and Pagination since they all used `aria-label`. The labels will default to 'Carousel {guid} Controls' (where `{guid}` is replace with the current instance's GUID) and you can customize them with an option, like so:

```
{
  labels: {
    controls: 'Photo Gallery {guid} Controls',
    pagination: 'Photo Gallery {guid} Pagination'
  }
}
```

The `{guid}` replacement is totally optional when customizing, but should help with the duplicate label issues (unless you plan on manually iterating them in the instance options). 

This is currently on the dev branch, and will land in the next release.

**Comment by nhall** [comment]
This sounds great!  Thank you!!
