### ISSUE TITLE
Only the drop area is visible

### ISSUE THREAD

**Issue by ghost** [Formstone/Formstone#252]
I created a very basic upload page. The only things on it are the upload references and the needed code.

I am using a licensed version on my side, but to show what I am talking about, I created a jsbin that behaves exactly as mine is.

http://jsbin.com/dujabefomu/edit?html,js,output

Notice there is no Completed, Queued, or Cancel All. So when the user drops files, they don't see anything that indicates it has been uploaded.

**Comment by benplum** [comment]
The complete/queued/cancel from the demo is a custom implementation based on the callback and events triggered by the plugin - these elements are not drawn for you, rather the plugin gives you an API to implement them on your site. The plugin is working, you can check the network panel to see the AJAX request. Here's a version that works with the elements, scripts, and styles from the demos:

http://jsbin.com/zozohuqixo/1/edit?js,output

One thing to note, since the upload target in your example (Ajax.ashx) doesn't exists on JSBin there is no response to display. You'll need to point this at a live URL that can handle the upload and return a response. The response can then be handled in the 'onFileComplete' function. 

I can see how this is confusing based on what is presented in the docs, we'll work on adding more details on how to implement.
