### ISSUE TITLE
Carousel JS error - Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by nhall** [Formstone/Formstone#258]
I've been using the carousel updates made in 1.4.8. In order to have the carousel items only move within the carousel boundaries I've removed `matchWidth` and and controlling the width of the elements by setting an explicit `flex-basis`. This works very well except when the carousel is size smaller than the `flex-basis` width. There error I get is:

> Cannot read property 'left' of undefined

I'm pretty sure [this is the problem](https://github.com/Formstone/Formstone/blob/master/src/js/carousel.js#L458). However, I am not sure why it's an issue. The first item should be defined and I should be able to get its left position.

I set up a [codepen illustrating the problem](https://codepen.io/nhall/pen/XyWjeW). I have the carousel items set to have a `flex-basis` of 310px so if you were to resize your browser to less than 310px you would see the JavaScript error.

**Comment by benplum** [comment]
At first glance, I think it may be tied to the paging logic: 

`if ( (width + iWidth > data.containerWidth + data.itemMargin) || (data.paged && i > 0) ) {`

This should probably take into account if there are any `$items` (since the item width is going to be greater then the container width at screen sizes less then 310px, based on your example):

`if ( ($items.length && width + iWidth > data.containerWidth + data.itemMargin) || (data.paged && i > 0) ) {`

I can test when I have a chance, but let me know if you find out anything more.

**Comment by nhall** [comment]
Thanks, Ben.
I'm testing this out and so far so good. I'll follow up with another comment as I test.

Thanks!

**Comment by benplum** [comment]
Fixed in 1.4.11.
