### ISSUE TITLE
Dropdown not working inside a container with horizontal scroll

### ISSUE THREAD

**Issue by rftb** [Formstone/Formstone#264]
We have a form that has the select with options styled using Formstone. That select is within a container that we want to have a width 100% and not be responsive, so we added the scrollbar.js to the container for the custom scroll bar.  The problem is that the custom scrollbar appears fine, but the select within it is blank.  If we disable the javascript for the container scrollbar, the select works fine again.  Is this possible to have both within each other? Maybe a way to disable scroll on the select?
![screen shot 2019-02-15 at 12 51 44 pm](https://user-images.githubusercontent.com/2086371/52877827-bd878300-3120-11e9-89c0-25757379eff7.png)

**Comment by benplum** [comment]
Can you share a codepen or live link?

**Comment by rftb** [comment]
@benplum Here is a link to a codepen I put together that shows what it is doing.  https://codepen.io/bbowman02/pen/XOOpra

**Comment by benplum** [comment]
Interesting. Looks like this has to do with the nested Dropdown's Scrollbar inheriting the horizontal styles from the containing vertical Scrollbar. 

I just pushed a fix for this. You will need to update to 1.4.12 and double check your styles since it required adding specificity to the Scrollbar selectors.
