### ISSUE TITLE
Lightbox - Vimeo link doesn't add "?" and causes player script to fail

### ISSUE THREAD

**Issue by matthisamoto** [Formstone/Formstone#278]
I end up with a URL formatted like this:

`https://player.vimeo.com/video/[video_id]&enablejsapi=1&origin=[origin]`

So it never adds the "?" to kick off the query vars string, note the presence of only "&" in the string. My origin URLs I've used were both the standard Vimeo URL and the player URL, without any additional query vars added:

`https://vimeo.com/[video_id]` 
or 
`https://player.vimeo.com/video/[video_id]`

It probably has to do with [this line](https://github.com/Formstone/Formstone/blob/b158589cccf4d159189bb7d5b4e4e53df38f9381/src/js/lightbox.js#L981) where it wants 2 or more array entries. My URLs would only have a length of 1, but still needs the "?" added.

**Comment by matthisamoto** [comment]
I'm currently circumventing this by adding `?rel=0` to the end of my source URL.

**Comment by benplum** [comment]
This appears to be expected behavior - does Vimeo provide URLs without the question mark?

**Comment by matthisamoto** [comment]
[This line](https://github.com/Formstone/Formstone/blob/b158589cccf4d159189bb7d5b4e4e53df38f9381/src/js/lightbox.js#L1573) appears to accept a normal Vimeo link,(`https://vimeo.com/[whatever]`) so I think my expectation was that this was intended to be able to parse one into the necessary parts.

And further, if we're extracting the video ID from a normal or embed link, and constructing our own player link from that, I guess we could end up with one with no vars?

**Comment by benplum** [comment]
That pattern strips the URL to down just the `player.vimeo.com/video/[video_id]` part. Later, the original query string is then [preserved](https://github.com/Formstone/Formstone/blob/b158589cccf4d159189bb7d5b4e4e53df38f9381/src/js/lightbox.js#L976). 

I think the issue is that the '&' is breaking the pattern matching since the video ID is not terminated by a slash, empty space, or question mark:

![Screen Shot 2020-10-06 at 2 18 38 PM](https://user-images.githubusercontent.com/1130075/95243692-00f3a100-07df-11eb-91f2-d08dff56e88c.png)
![Screen Shot 2020-10-06 at 2 18 43 PM](https://user-images.githubusercontent.com/1130075/95243699-0355fb00-07df-11eb-85a6-42ab1420dd54.png)

The solution would be to use the query string: `https://player.vimeo.com/video/[video_id]?enablejsapi=1&origin=[origin]`
