### ISSUE TITLE
Dropdown not working with desktop touch screens

### ISSUE THREAD

**Issue by pensiero** [Formstone/Formstone#61]
If you have a desktop pc that has touch screen, dropdown seems not to work. Probably is because the library thinks that we are in a desktop environment, and not in a tablet/smartphone environment (with touch).

Tried with Windows 7 and Chrome.

**Comment by benplum** [comment]
On touch devices the default select interaction should be triggered. I don't have a windows 7 touch device to test on - is the Modernizer touch class added to the body? Or is it no-touch?

**Comment by pensiero** [comment]
Yes, is 'no-touch' but no, I didn't add the Modernizer touch class to the body, do I have to do so?

**Comment by benplum** [comment]
I think this is related to another open bug (https://github.com/Formstone/Formstone/issues/63) and has to do with incorrect touch support reporting by the OS. I'll look into another solution for detecting touch devices.

**Comment by pensiero** [comment]
Thanks

**Comment by pensiero** [comment]
At the end, how you solve it? Do you still use the 'no-touch' class of Modernizr? Thanks

**Comment by benplum** [comment]
So I think the issue is that some browsers are reporting touch support even if the current device doesn't have a touch input. This sort of makes sense, because the touch api is always available on these browsers, you just can't use it. It's now just listening for both touch and click at the same time and will act on which ever is fired. I'm not seeing any issues after a few days of testing but let me know if you run into any problems with the change.

**Comment by pensiero** [comment]
Thanks a lot, I will try!
